[package]
name = "k562"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.7"
anyhow = "1.0" 
reqwest = { version = "0.12", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }